In [1]:
import sys
from __future__ import division

In [2]:
import numpy as np
from openLoop.utilities.ipynb.displays import *
#from YALL.utilities.tabulate import tabulate

import declarative

from declarative.bunch import (
    DeepBunch
)

import openLoop.math.dispatched as dmath 
#import openLoop.math.dispatch_sympy

Populating the interactive namespace from numpy and matplotlib


In [3]:
import openLoop.utilities.version as version
print(version.foundations_version())

from openLoop.utilities.np import logspaced

from openLoop import optics
from openLoop import base 
from openLoop import signals 
from openLoop import system
from openLoop import readouts 
from openLoop import mechanical

b'2017-04-02 22:41:49 -0400 (87cf294591536591a3d2b62cc64392752bb95e54)'


In [10]:
mechanical.XYZMass

openLoop.mechanical.xyz.XYZMass

In [26]:
100 / 6.28

15.92356687898089

In [50]:
(31.376 + 44.82)/2

38.098

In [126]:
B = np.matrix([
    [-1, 1, 0], 
    [0, -1, 1], 
    [-1, 0, 1], 
    [1, 1, -1],
    [1, -1, 1],
    [-1, 1, 1],
])
A = np.matrix([
    [1, -1, 0 ], 
    [0, 1, -1], 
    [1, 0, -1], 
    [1, 1, -1],
    [1, -1, 1],
    [-1, 1, 1],
])
X = np.linalg.pinv(B) * A

In [127]:
np.linalg.det(X)

0.020408163265306117

In [191]:
Y = np.matrix([[-2,1,1],[1,-2,1],[1,1,-2]])
X = 100e3
Y = Y * X
I = np.eye(3)
print((I - Y) * np.linalg.inv(I + Y) )

np.linalg.eig(I + Y)
#print(( - Y) * np.linalg.inv( + Y) )

[[-0.33333778  0.66666889  0.66666889]
 [ 0.66666889 -0.33333778  0.66666889]
 [ 0.66666889  0.66666889 -0.33333778]]


(array([ -2.99999000e+05,   1.00000000e+00,  -2.99999000e+05]),
 matrix([[-0.81649658,  0.57735027, -0.19970487],
         [ 0.40824829,  0.57735027, -0.58577755],
         [ 0.40824829,  0.57735027,  0.78548242]]))

In [189]:
np.linalg.inv(I/X + Y/X)

matrix([[ 33333.11110991,  33333.44444436,  33333.44444436],
        [ 33333.44444436,  33333.11110991,  33333.44444436],
        [ 33333.44444436,  33333.44444436,  33333.11110991]])

In [161]:
Y

matrix([[ 1. ,  0.5,  0.5],
        [ 0.5,  1. ,  0.5],
        [ 0.5,  0.5,  1. ]])

In [214]:
vx = np.matrix([1,1,1]) / 3**.5
P_x = vx.T * vx
P_x
E = 2 * P_x - I

In [332]:
vx = np.matrix([1,1,1]) / 3**.5
P_x = vx.T * vx
P_x
E = 2 * P_x - I
X = np.bmat([E,I])
VIAB = np.bmat([[I,I],[I,-I]])
XVI = X * np.linalg.inv(VIAB) 
XV = XVI[:,0:3]
XI = XVI[:,3:6]

In [333]:
np.linalg.inv(XI) * XV

matrix([[  9.00719925e+14,   9.00719925e+14,   9.00719925e+14],
        [  9.00719925e+14,   9.00719925e+14,   9.00719925e+14],
        [  9.00719925e+14,   9.00719925e+14,   9.00719925e+14]])

In [334]:
XV * 3 /2

matrix([[ 0.5,  0.5,  0.5],
        [ 0.5,  0.5,  0.5],
        [ 0.5,  0.5,  0.5]])

In [335]:
XI * 3 / 2

matrix([[-1. ,  0.5,  0.5],
        [ 0.5, -1. ,  0.5],
        [ 0.5,  0.5, -1. ]])

In [336]:
X2VI = np.bmat([np.zeros((3,3)), np.ones((3,3)) - 2 * I])# * VIAB.T
np.linalg.inv(X2VI[:,0:3]) * X2VI[:,3:6]

LinAlgError: Singular matrix

In [337]:
X2VI

matrix([[ 0.,  0.,  0., -1.,  1.,  1.],
        [ 0.,  0.,  0.,  1., -1.,  1.],
        [ 0.,  0.,  0.,  1.,  1., -1.]])

In [346]:
X2VI = np.matrix([
    [0,0,0,1,1,1],
    [0,1,-1,0,0,0,],
    [1,-1,0,0,0,0]]) * VIAB.T
print(np.linalg.inv(X2VI[:,0:3]) * X2VI[:,3:6])
print(np.linalg.inv(X2VI[:,3:6]) * X2VI[:,0:3])

[[ 0.33333333 -0.66666667 -0.66666667]
 [-0.66666667  0.33333333 -0.66666667]
 [-0.66666667 -0.66666667  0.33333333]]
[[ 0.33333333 -0.66666667 -0.66666667]
 [-0.66666667  0.33333333 -0.66666667]
 [-0.66666667 -0.66666667  0.33333333]]


In [361]:
I = np.eye(3)
VIAB = np.bmat([[I,I],[I,-I]])
X2VI = np.matrix([
    [0,0,0,1,1,1],
    [0,1,-1,0,0,0,],
    [1,-1,0,0,0,0],
    [1,0,-1,0,0,0],
]) * VIAB.T
print(np.linalg.pinv(X2VI[:,0:3]) * X2VI[:,3:6])
print(np.linalg.pinv(X2VI[:,3:6]) * X2VI[:,0:3])

[[ 0.33333333 -0.66666667 -0.66666667]
 [-0.66666667  0.33333333 -0.66666667]
 [-0.66666667 -0.66666667  0.33333333]]
[[ 0.33333333 -0.66666667 -0.66666667]
 [-0.66666667  0.33333333 -0.66666667]
 [-0.66666667 -0.66666667  0.33333333]]


In [369]:
I = np.eye(3)
VIAB = np.bmat([[I,I],[I,-I]])
d = 5
X2VI = np.matrix([
    [0,0,0,1,1/d,1],
    [0,d,-1,0,0,0,],
    [1,0,-1,0,0,0],
]) * VIAB.T
print(np.linalg.inv(X2VI[:,0:3]) * X2VI[:,3:6])
print(np.linalg.inv(X2VI[:,3:6]) * X2VI[:,0:3])
np.linalg.eig(np.linalg.inv(X2VI[:,0:3]) * X2VI[:,3:6])

[[ 0.01960784 -0.19607843 -0.98039216]
 [-0.19607843  0.96078431 -0.19607843]
 [-0.98039216 -0.19607843  0.01960784]]
[[ 0.01960784 -0.19607843 -0.98039216]
 [-0.19607843  0.96078431 -0.19607843]
 [-0.98039216 -0.19607843  0.01960784]]


(array([ 1., -1.,  1.]), matrix([[ 0.71400555, -0.70014004,  0.51870247],
         [-0.13730876, -0.14002801, -0.77360539],
         [-0.6865438 , -0.70014004, -0.36398139]]))

In [359]:
I = np.eye(4)
VIAB = np.bmat([[I,I],[I,-I]])
X2VI = np.matrix([
    [0,0,0,0,1,1,1,1],
    [0,1,-1,0,0,0,0,0,],
    [1,-1,0,0,0,0,0,0],
    #[1,0,-1,0,0,0,0,0],
    #[0,1,-1,0,0,0,0,0],
    [0,0,1,-1,0,0,0,0],
]) * VIAB.T
print(np.linalg.pinv(X2VI[:,0:4]) * X2VI[:,4:8])
print(np.linalg.pinv(X2VI[:,4:8]) * X2VI[:,0:4])

[[ 0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]
[[ 0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]


In [341]:
X2VI

matrix([[ 1.,  1.,  1., -1., -1., -1.],
        [ 0.,  1., -1.,  0.,  1., -1.],
        [ 1., -1.,  0.,  1., -1.,  0.]])

In [342]:
VIAB.T

matrix([[ 1.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  1.],
        [ 1.,  0.,  0., -1., -0., -0.],
        [ 0.,  1.,  0., -0., -1., -0.],
        [ 0.,  0.,  1., -0., -0., -1.]])